const constants = {
  ADD_DAY: 'ADD_DAY',
  FETCH_RESORT_NAME: 'FETCH_RESORT_NAME',
  CANCLE_FETCH: 'CANCLE_FETCH',
  CHANGE_SUGGESTION: 'CHANGE_SUGGESTION',
  CLEAR_SUGGESTION: 'CLEAR_SUGGESTION',
  SET_GOAL: 'SET_GOAL',
  REMOVE_DAY: 'REMOVE_DAY',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default constants;
